[build]
target = "target.json" # Fallback to custom target if needed, but our Makefile passes --target

[target.x86_64-unknown-none]
rustflags = [
    "--cfg", "poly1305_force_soft",
    "--cfg", "chacha20_force_soft"
]
