// ============================================================
// Brane OS Kernel — Cooperative Context Switching
// ============================================================
//
// Implements task context save/restore for cooperative
// multitasking between kernel tasks.
//
// Design:
//   - Each task has a `TaskContext` that holds all callee-saved
//     registers (rbx, r12–r15, rbp, rsp, rip).
//   - `switch_context(old, new)` saves current CPU state into
//     `*old`, then restores from `*new` and transfers control.
//   - Cooperative: a task voluntarily calls `yield_current()`
//     or signals a block condition to trigger a switch.
//
// Register set saved (System V AMD64 ABI callee-saved):
//   rbx, r12, r13, r14, r15, rbp, rsp + rip (return address)
//
// Caller-saved registers (rax, rcx, rdx, rsi, rdi, r8–r11)
// are NOT preserved — they are ephemeral across a yield.
//
// Spec reference: ARCHITECTURE.md §5.2.3 (Scheduler)
//                 ROADMAP.md Fase 10 (Context switching real)
// ============================================================

#![allow(dead_code)]

// -----------------------------------------------------------------------
// TaskContext — saved CPU register state
// -----------------------------------------------------------------------

/// Saved CPU context for a kernel task (x86_64).
///
/// Field order matches the byte offsets used in the naked asm below:
///   rbx  @ offset 0x00
///   r12  @ offset 0x08
///   r13  @ offset 0x10
///   r14  @ offset 0x18
///   r15  @ offset 0x20
///   rbp  @ offset 0x28
///   rsp  @ offset 0x30
///   rip  @ offset 0x38
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct TaskContext {
    pub rbx: u64,
    pub r12: u64,
    pub r13: u64,
    pub r14: u64,
    pub r15: u64,
    pub rbp: u64,
    pub rsp: u64,
    pub rip: u64,
}

impl TaskContext {
    /// Create an empty (zeroed) context.
    ///
    /// Used for the initial boot task (which reuses the bootloader stack)
    /// or as a placeholder before a task is fully set up.
    pub const fn empty() -> Self {
        Self {
            rbx: 0,
            r12: 0,
            r13: 0,
            r14: 0,
            r15: 0,
            rbp: 0,
            rsp: 0,
            rip: 0,
        }
    }

    /// Create a context for a new task.
    ///
    /// `stack_top` — the virtual address of the *top* (highest address)
    ///               of the task's pre-allocated stack.
    /// `entry`     — function address where the task begins executing.
    ///
    /// Internally we set `rsp = stack_top - 8` so the CPU's `ret`
    /// instruction inside `switch_context` pops the entry address and
    /// jumps there, simulating a fresh function call.
    pub fn new_task(stack_top: u64, entry: u64) -> Self {
        Self {
            rbx: 0,
            r12: 0,
            r13: 0,
            r14: 0,
            r15: 0,
            rbp: stack_top,
            rsp: stack_top - 8, // space for the "return address"
            rip: entry,
        }
    }
}

// -----------------------------------------------------------------------
// switch_context — the core asm switch primitive
// -----------------------------------------------------------------------

/// Cooperative context switch (x86_64).
///
/// Saves callee-saved registers of the **current** task into `*old_ctx`,
/// then restores registers from `*new_ctx` and jumps into the new task.
///
/// Calling convention (System V AMD64):
///   rdi = old_ctx : *mut TaskContext
///   rsi = new_ctx : *const TaskContext
///
/// # Safety
///
/// Both pointers must be valid, non-null, properly aligned `TaskContext`
/// values backed by live storage for the entire task lifetime.  
/// The scheduler lock MUST NOT be held by the calling thread when this
/// function executes, to prevent deadlock when the new task tries to
/// acquire it.
#[cfg(target_arch = "x86_64")]
#[naked]
pub unsafe extern "C" fn switch_context(
    old_ctx: *mut TaskContext,     // rdi
    new_ctx: *const TaskContext,   // rsi
) {
    // NAKED function — no prologue/epilogue generated by the compiler.
    core::arch::naked_asm!(
        // ── Save current task into *old_ctx ──────────────────────────
        "mov [rdi + 0x00], rbx",
        "mov [rdi + 0x08], r12",
        "mov [rdi + 0x10], r13",
        "mov [rdi + 0x18], r14",
        "mov [rdi + 0x20], r15",
        "mov [rdi + 0x28], rbp",
        "mov [rdi + 0x30], rsp",
        // The return address (where the caller will resume) is the
        // value currently on top of the stack.
        "mov rax, [rsp]",
        "mov [rdi + 0x38], rax",

        // ── Restore new task from *new_ctx ────────────────────────────
        "mov rbx, [rsi + 0x00]",
        "mov r12, [rsi + 0x08]",
        "mov r13, [rsi + 0x10]",
        "mov r14, [rsi + 0x18]",
        "mov r15, [rsi + 0x20]",
        "mov rbp, [rsi + 0x28]",
        "mov rsp, [rsi + 0x30]",
        // Load the new task's RIP into rax and jump.
        // We use `jmp` rather than manipulating the stack so that we
        // don't disturb the new task's stack layout.
        "mov rax, [rsi + 0x38]",
        "jmp rax",
    );
}

/// No-op stub for non-x86_64 targets (used when running unit tests on host).
#[cfg(not(target_arch = "x86_64"))]
pub unsafe extern "C" fn switch_context(
    _old_ctx: *mut TaskContext,
    _new_ctx: *const TaskContext,
) {
    // Context switching requires bare-metal x86_64; not meaningful on host.
}

// -----------------------------------------------------------------------
// KernelStack — a fixed-size, heap-allocated task stack
// -----------------------------------------------------------------------

/// A fixed-size kernel stack aligned to the System V AMD64 ABI requirement.
///
/// Stacks grow downward on x86_64, so `top()` returns the highest
/// valid address (the initial value of RSP before the first push).
#[repr(C, align(16))]
pub struct KernelStack {
    data: [u8; KernelStack::SIZE],
}

impl KernelStack {
    /// Each kernel task stack is 16 KiB — sufficient for typical kernel call
    /// chains without being excessively wasteful.
    pub const SIZE: usize = 16 * 1024;

    pub const fn new() -> Self {
        Self {
            data: [0u8; Self::SIZE],
        }
    }

    /// Address of the top of this stack (highest valid byte + 1).
    ///
    /// The CPU expects RSP to point here before any `push` or `call`.
    /// We align down to 16 bytes as required by the ABI.
    pub fn top(&self) -> u64 {
        let base = self.data.as_ptr() as u64;
        (base + Self::SIZE as u64) & !0xF
    }
}

impl Default for KernelStack {
    fn default() -> Self {
        Self::new()
    }
}
